

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Building
    {
        public Building()
        {
            this.Rooms = new HashSet<Room>();
        }

        [Required(ErrorMessage = "Building Code is a required field")]
        [StringLength(10, ErrorMessage = "Module Code should be between 1 and 6 characters.", MinimumLength = 1)]
        public string BuildingCode { get; set; }

        [Required(ErrorMessage = "Name is a required field")]
        [StringLength(30, ErrorMessage = "Module Code should be between 1 and 30 characters.", MinimumLength = 1)]
        public string Name { get; set; }

        public string ParkCode { get; set; }

        public virtual ICollection<Room> Rooms { get; set; }
    }
}

