//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.RequiredFacilities = new HashSet<RequiredFacility>();
            this.RoomFacilities = new HashSet<RoomFacility>();
        }
    
        public int FacilityID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RequiredFacility> RequiredFacilities { get; set; }
        public virtual ICollection<RoomFacility> RoomFacilities { get; set; }
    }
}
