//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.AllocatedRooms = new HashSet<AllocatedRoom>();
        }
    
        public int RoomID { get; set; }
        public string BuildingCode { get; set; }
        public string Name { get; set; }
        public string RoomType { get; set; }
        public string SeatingType { get; set; }
        public int Capacity { get; set; }
    
        public virtual ICollection<AllocatedRoom> AllocatedRooms { get; set; }
        public virtual Building Building { internal get; set; }
    }
}
