//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablingSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public int SemesterID { get; set; }
        public int StartYear { get; set; }
        public byte SemesterNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
